name: ubuntu-calendar-app
version: 0.1
summary: Ubuntu calendar app
description: Ubuntu calendar app
confinement: devmode  # use "strict" to enforce system access only via declared interfaces
grade: devel

apps:
    ubuntu-calendar-app:
        command: desktop-launch $SNAP/bin/ubuntu-calendar-app --desktop_file_hint=unity8 "$@"
        plugs: [platform, gsettings, unity7, opengl]

plugs:
    platform:
        interface: content
        content: ubuntu-app-platform1
        target: ubuntu-app-platform
# eds-calendar and address-book not available yet. 
# FIXME: Fixt that after these interfaces appear on syncd
#    eds-calendar:
#        interface: eds
#        service: calendar
#    address-book:
#        interface: address-book

parts:
    ubuntu-calendar-app:
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
        source: .
        build-packages:
            - cmake
            - intltool
        stage-packages: []
            # - accountsservice
            #- accountsservice-ubuntu-schemas
            #- account-plugin-google
            #- qmlscene
            #- qml-module-qt-labs-settings
            #- qml-module-qtcontacts
            #- qml-module-qtorganizer
            #- qml-module-ubuntu-components
            #- qml-module-ubuntu-onlineaccounts
            #- qml-module-ubuntu-onlineaccounts-client
            #- qtdeclarative5-ubuntu-content1
            #- qtdeclarative5-ubuntu-syncmonitor0.1
            #- qtcontact5-galera
            #- qtorganizer5-eds
            #- qtubuntu-desktop
            #- suru-icon-theme
            #- mir-graphics-drivers-desktop
        snap: []
        after: [desktop-ubuntu-app-platform]

    desktop-ubuntu-app-platform:
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: qt
        plugin: make
        make-parameters: ["FLAVOR=qt5-app-platform"]
        # developer should use stable-phone-overlay PPA for Qt 5.6 to match the platform snap
        build-packages:
          - qtbase5-dev
          - dpkg-dev

    environment:
        source: snap/
        plugin: dump
        organize:
            ubuntu-calendar-app.wrapper: bin/ubuntu-calendar-app
