name: ubuntu-calendar-app
version: 0.1
summary: Ubuntu calendar app
description: Ubuntu calendar app
confinement: strict  # use "strict" to enforce system access only via declared interfaces
grade: devel

apps:
    ubuntu-calendar-app:
        command: desktop-launch $SNAP/bin/ubuntu-calendar-app --desktop_file_hint=unity8 "$@"
        plugs: [gsettings, unity7, opengl, ubuntu-qt-runtime]

plugs:
#    gsettings:
#        interface: gsettings
#    unity7:
#        interface: unity7
#    opengl:
#        interface: opengl
    ubuntu-qt-runtime:
        interface: content
        content: ubuntu-qt-runtime
        target: ubuntu-qt-runtime
# eds-calendar and address-book not available yet. 
# FIXME: Fixt that after these interfaces appear on syncd
#    eds-calendar:
#        interface: eds
#        service: calendar
#    address-book:
#        interface: address-book

parts:
    ubuntu-calendar-app:
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
        source: .
        build-packages:
            - cmake
            - intltool
        stage-packages:
            - accountsservice
            - accountsservice-ubuntu-schemas
            - account-plugin-google
            #- qmlscene
            #- qml-module-qt-labs-settings
            #- qml-module-qtcontacts
            #- qml-module-qtorganizer
            #- qml-module-ubuntu-components
            #- qml-module-ubuntu-onlineaccounts
            #- qml-module-ubuntu-onlineaccounts-client
            #- qtdeclarative5-ubuntu-content1
            #- qtdeclarative5-ubuntu-syncmonitor0.1
            #- qtcontact5-galera
            #- qtorganizer5-eds
            #- qtubuntu-desktop
            #- suru-icon-theme
            #- mir-graphics-drivers-desktop
        filesets:
            includedfiles:
                - "ubuntu-qt-runtime/*"
        snap:
            - -usr/lib/python3
            - -usr/share/doc
            - -usr/include  
            - "$includedfiles"         
        after: [desktop-gtk3]

    environment:
        source: .
        plugin: dump
        organize:
            ubuntu-calendar-app.wrapper: bin/ubuntu-calendar-app
