name: ubuntu-calendar-app
version: 0.1.1
summary: Ubuntu calendar app
description: Ubuntu calendar app
confinement: devmode  # use "strict" to enforce system access only via declared interfaces
grade: devel
architectures: [all]

apps:
    ubuntu-calendar-app:
        command: desktop-launch qmlscene "$@" $SNAP/usr/share/calendar-app/calendar.qml
        plugs: [home, gsettings, opengl, platform, unity7, unity8, mir]

plugs:
    platform:
        interface: content
        content: ubuntu-app-platform1
        target: ubuntu-app-platform
        default-provider: ubuntu-app-platform
# eds-calendar and address-book not available yet. 
# FIXME: Fixt that after these interfaces appear on syncd
#    eds-calendar:
#        interface: eds
#        service: calendar
#    address-book:
#        interface: address-book

parts:
    ubuntu-calendar-app:
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
        source: .
        build-packages:
            - cmake
            - intltool
        stage-packages: []
        after: [desktop-ubuntu-app-platform]

    environment:
        source: snap/
        plugin: dump
